@startuml

class プレイヤー {
    - id
}
class 主人公 {
    - 名前
    - レベル
    - 攻撃力
    - 発動中の効果
    - 必殺技ゲージ
    - 現在のステージ
    - 所持光数
    - 所持英傑石数
    - 次のレベルアップに必要なコスト
    - ボスに負けた事があるかどうか
    - 所持レリック数（仮）
    + レベルを上げる()
    + オフラインボーナスを受けとる()
}
note top {
    必殺技発動のコード例:
    function 主人公:必殺技を発動(必殺技A)
       効果 = 必殺技A:発動()
       if 効果.ステージ向け then
         self.ステージ.発動中効果:insert(効果)
       elseif 効果.主人公向け then
         self.主人公.発動中効果:insert(効果)
       end
    end
}

class ステージ {
    - 敵軍HP
    - ボスHP
    - 敵軍の数
    - 敵軍が落とすコインの数
    - ボスが落とすコインの数
    - 倒した敵の数
}
note bottom: 各ステージの敵軍の種類はランダムに出現する

abstract 敵 {
    - 名前
    - 画像URI
    - 残りHP
}
class ボス
class 敵軍
ボス -u-|> 敵
敵軍 -u-|> 敵

class 武将 {
    - 名前
    - レベル
    - 開放済みかどうか
    - 1秒あたりの攻撃回数
    - DPS
    + レベルを上げる()
    + 開放可能スキルを取得する()
}
class スキル {
    - 名前
}
class 所持スキル {
    - 開放可能レベル
    - 解放済みかどうか
}
class 必殺技 {
    - 名前
    - 説明
    - 開放可能主人公レベル
    - レベル
    - レベルアップに必要な光の数量
    - 解放済みかどうか
    + レベルアップする()
}
class ダメージ系必殺技 {
    - ダメージ倍率
}
class インセンティブ系必殺技 {
    - 種別
    - 数量
}
ダメージ系必殺技 --|> 必殺技
パラメータ系必殺技 --|> 必殺技
インセンティブ系必殺技 --|> 必殺技
MP回復系必殺技 --|> 必殺技

class アイテム {
    - 名前
    - 消費するもの
    - 価格
    - 効果発動中かどうか
    - 効果発動時刻
    - 回復までの時間
    - 発動にかかる時間
}
note bottom {
    動画広告視聴ですぐに回復する

    消費するもの: お金、英傑石
}

class 倍率変更効果 {
    - 倍率
    - 対象数値
    - 持続時間
    - 効果の対象
}
note bottom {
    必殺技、スキル、アイテムのどれか一つにだけ属する

    対象数値: 「攻撃力」「コイン数」など
    効果の対象: 「主人公」「武将」「ステージ」のどれか
    持続時間: 1(秒) ~ 無限
}
class オフラインボーナス {
    - ボーナスコイン数
    - オフライン開始時刻
    - オフライン終了時刻
    + 動画広告かどうか
}
note bottom {
 オフライン終了時にボーナスのコイン数を計算する
 ステージの進捗度に応じて動画広告を見せるかどうか決める
}

class ボーナス
class 必殺技系ボーナス
class インセンティブ系ボーナス {
    - 種別
    - 数量
    - 動画広告かどうか
}
note bottom: 種別: 光、英傑石
class パラメータ系ボーナス
必殺技系ボーナス --|> ボーナス
インセンティブ系ボーナス --|> ボーナス
パラメータ系ボーナス --|> ボーナス

class ボーナス出現管理 {
    - ボーナス出現間隔
    + 出現中のボーナス
}
note bottom: シングルトン

class 商品 {
    - 価格
    - 英傑石数
    - 説明文
}

必殺技 "0..1" o-- "1" 倍率変更効果
スキル "0..1"  o-- "1" 倍率変更効果
アイテム "0..1" o-- "1" 倍率変更効果
武将 "1" -- "*" 所持スキル
所持スキル "*" -- "1" スキル
ステージ *--> 敵: 生成
主人公 --> 敵: 攻撃する
主人公 o--> 必殺技: 発動する\nレベルアップ\n開放する\n回復する
主人公 o--> 武将: 開放する\nレベルアップ
主人公 o--> ステージ: 進む(=生成する)
主人公 o--> オフラインボーナス: 開始\n終了(武将[])
主人公 --> ボーナス: 取得
主人公 --> アイテム: 取得(英傑石)
ボーナス出現管理 -u-> ボーナス: 出現させる
ボーナス出現管理 --> 主人公
プレイヤー -l-> 商品: 購入する
プレイヤー --> 主人公: 商品を付与
必殺技系ボーナス --> 必殺技
パラメータ系必殺技 --> 倍率変更効果

@enduml